### ISSUE TITLE
[FEAT] iOS 0차 과제

### ISSUE THREAD

**Issue by hryeong66** [29th-WE-SOPT-iOS-Part/JangHyeRyeong#1]
## 📌  Feature Issue
 
1차 과제는 이런 과제입니다~!
이 부분은 제가 기본으로 노션에 넣어놓을 예정입니다.
사용하실 분들은 복사해서 붙여넣고 필요한 부분 추가하면 좋을 것 같아요~!

## 📝  To-do

- [ ] Xcode 13 update 하기
- [ ] 이 부분은 엔터를 치면
- [ ] 자동으로 to - do가 생겨요 like notion
